import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { UserService } from '../services/userService';
import { unifiedSyncService } from '../services/unifiedSyncService';
import AsyncStorage from '@react-native-async-storage/async-storage';
import Logger from '../utils/logger';

// 创建页面专用日志器
const logger = Logger.forPage('AuthContext');

interface UserInfo {
  id: string;
  nickname?: string;
  phone?: string;
  email?: string;
  avatar?: string;
  loginType?: 'wechat' | 'apple' | 'phone' | 'guest';
  token?: string;
  createdAt?: string;
  updatedAt?: string;
  learningStats?: {
    level?: number;
    totalWords?: number;
    masteredWords?: number;
    learningDays?: number;
    currentStreak?: number;
    totalReviews?: number;
    accuracy?: number;
  };
}

interface AuthContextType {
  user: UserInfo | null;
  loginType: string | null;
  isAuthenticated: boolean;
  login: (userData: UserInfo, type: string) => Promise<void>;
  logout: () => Promise<void>;
  updateUser: (userData: Partial<UserInfo>) => void;
  getAuthToken: () => Promise<string | null>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within AuthProvider');
  return ctx;
};

export const AuthProvider = ({ children }: { children: ReactNode }) => {
  const [user, setUser] = useState<UserInfo | null>(null);
  const [loginType, setLoginType] = useState<string | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const userService = UserService.getInstance();

  // 初始化时加载用户信息
  useEffect(() => {
    loadUserInfo();
  }, []);

  const loadUserInfo = async () => {
    try {
      logger.log('loadUserInfo 开始', 'loadUserInfo');
      const userLoginInfo = await userService.getUserLoginInfo();
      if (userLoginInfo) {
        logger.log('找到用户数据', 'loadUserInfo');
        
        // 验证token是否有效
        const token = await userService.getAuthToken();
        if (token) {
          // 导入tokenValidationService
          const { TokenValidationService } = await import('../services/tokenValidationService');
          const tokenValidationService = TokenValidationService.getInstance();
          const validation = await tokenValidationService.validateToken(token);
          
          if (validation.isValid) {
            logger.log('token验证通过，设置认证状态', 'loadUserInfo');
            setUser(userLoginInfo.userData);
            setLoginType(userLoginInfo.loginType);
            setIsAuthenticated(true);
          } else {
            logger.log('token验证失败，清除无效数据', 'loadUserInfo');
            // token无效，清除数据
            await userService.clearUserLoginInfo();
            setUser(null);
            setLoginType(null);
            setIsAuthenticated(false);
          }
        } else {
          logger.log('没有找到token，清除认证状态', 'loadUserInfo');
          setUser(null);
          setLoginType(null);
          setIsAuthenticated(false);
        }
      } else {
        logger.log('没有找到用户数据', 'loadUserInfo');
        
        // 检查是否有自动生成的游客ID
        const autoGeneratedUserData = await AsyncStorage.getItem('userData');
        if (autoGeneratedUserData) {
          try {
            const parsedData = JSON.parse(autoGeneratedUserData);
            if (parsedData.isAutoGenerated && parsedData.loginType === 'guest') {
              logger.log('发现自动生成的游客ID', 'loadUserInfo');
              setUser(parsedData);
              setLoginType('guest');
              setIsAuthenticated(false); // 自动生成的用户需要手动登录才能获得token
            }
          } catch (error) {
            logger.error('解析自动生成的用户数据失败', 'loadUserInfo');
          }
        }
      }
    } catch (error) {
      logger.error('loadUserInfo 失败', 'loadUserInfo');
    }
  };

  const login = async (userData: UserInfo, type: string) => {
    try {
      logger.log('login 开始', 'login');
      await userService.saveUserLoginInfo(userData, type);
      logger.log('保存到本地存储完成', 'login');
      
      setUser(userData);
      setLoginType(type);
      setIsAuthenticated(true);
      
      logger.log('状态更新完成', 'login');
      
      // 新增：登录后同步本地历史到云端
      await unifiedSyncService.addToSyncQueue({
        type: 'searchHistory',
        data: await AsyncStorage.getItem('searchHistory') || [],
        userId: userData.id,
        operation: 'update',
        priority: 'high'
      });
      
      // 新增：登录后强制刷新订阅状态
      try {
        logger.log('开始刷新订阅状态...', 'login');
        const { subscriptionService } = await import('../services/subscriptionService');
        const status = await subscriptionService.checkSubscriptionStatus();
        logger.log('订阅状态已刷新', 'login');
        console.log('📊 刷新后的订阅状态:', status);
      } catch (error) {
        logger.error('刷新订阅状态失败', 'login');
        console.error('❌ 刷新订阅状态失败:', error);
      }
    } catch (error) {
      logger.error('login 失败', 'login');
      throw error;
    }
  };

  const logout = async () => {
    try {
      await userService.clearUserLoginInfo();
      setUser(null);
      setLoginType(null);
      setIsAuthenticated(false);
      
      // 清除订阅缓存
      try {
        const { subscriptionService } = await import('../services/subscriptionService');
        await subscriptionService.clearSubscriptionCache();
        logger.log('订阅缓存已清除', 'logout');
                } catch (error) {
                    logger.error('清除订阅缓存失败', 'logout');
                    console.error('❌ 清除订阅缓存失败:', error);
                }
    } catch (error) {
      console.error('登出失败:', error);
    }
  };

  const updateUser = (userData: Partial<UserInfo>) => {
    if (user) {
      setUser({ ...user, ...userData });
    }
  };

  const getAuthToken = async (): Promise<string | null> => {
    try {
      console.log('🔍 [AuthContext] getAuthToken 开始调用...');
      
      // 首先检查当前用户对象中的token
      if (user?.token) {
        console.log('🔍 [AuthContext] 从当前用户对象获取token:', user.token.substring(0, 20) + '...');
        return user.token;
      }
      
      // 然后尝试从userService获取
      const token = await userService.getAuthToken();
      console.log('🔍 [AuthContext] userService.getAuthToken 结果:', token ? `${token.substring(0, 20)}...` : 'null');
      
      // 如果userService获取失败，尝试直接从AsyncStorage获取
      if (!token) {
        console.log('🔍 [AuthContext] userService获取token失败，尝试直接从AsyncStorage获取...');
        try {
          const directToken = await AsyncStorage.getItem('authToken');
          console.log('🔍 [AuthContext] 直接从AsyncStorage获取的token:', directToken ? `${directToken.substring(0, 20)}...` : 'null');
          return directToken;
        } catch (directError) {
          console.error('❌ [AuthContext] 直接从AsyncStorage获取token也失败:', directError);
        }
      }
      
      return token;
    } catch (error) {
      console.error('❌ AuthContext getAuthToken 失败:', error);
      return null;
    }
  };

  return (
    <AuthContext.Provider value={{ user, loginType, isAuthenticated, login, logout, updateUser, getAuthToken }}>
      {children}
    </AuthContext.Provider>
  );
}; 