import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';
import { UserService } from '../services/userService';
import { unifiedSyncService } from '../services/unifiedSyncService';
import AsyncStorage from '@react-native-async-storage/async-storage';

interface UserInfo {
  id: string;
  nickname?: string;
  phone?: string;
  email?: string;
  avatar?: string;
  loginType?: 'wechat' | 'apple' | 'phone' | 'guest';
  createdAt?: string;
  updatedAt?: string;
  learningStats?: {
    level?: number;
    experience?: number;
    totalWords?: number;
    masteredWords?: number;
    learningDays?: number;
    currentStreak?: number;
    totalReviews?: number;
    accuracy?: number;
  };
}

interface AuthContextType {
  user: UserInfo | null;
  loginType: string | null;
  isAuthenticated: boolean;
  login: (userData: UserInfo, type: string) => Promise<void>;
  logout: () => Promise<void>;
  updateUser: (userData: Partial<UserInfo>) => void;
  getAuthToken: () => Promise<string | null>;
}

const AuthContext = createContext<AuthContextType | undefined>(undefined);

export const useAuth = () => {
  const ctx = useContext(AuthContext);
  if (!ctx) throw new Error('useAuth must be used within AuthProvider');
  return ctx;
};

export const AuthProvider = ({ children }: { children: ReactNode }) => {
  const [user, setUser] = useState<UserInfo | null>(null);
  const [loginType, setLoginType] = useState<string | null>(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const userService = UserService.getInstance();

  // 初始化时加载用户信息
  useEffect(() => {
    loadUserInfo();
  }, []);

  const loadUserInfo = async () => {
    try {
      console.log('🔍 AuthContext loadUserInfo 开始');
      const userLoginInfo = await userService.getUserLoginInfo();
      if (userLoginInfo) {
        console.log('🔍 AuthContext loadUserInfo 找到用户数据:', userLoginInfo);
        setUser(userLoginInfo.userData);
        setLoginType(userLoginInfo.loginType);
        setIsAuthenticated(true);
      } else {
        console.log('🔍 AuthContext loadUserInfo 没有找到用户数据');
        
        // 检查是否有自动生成的游客ID
        const autoGeneratedUserData = await AsyncStorage.getItem('userData');
        if (autoGeneratedUserData) {
          try {
            const parsedData = JSON.parse(autoGeneratedUserData);
            if (parsedData.isAutoGenerated && parsedData.loginType === 'guest') {
              console.log('🔍 发现自动生成的游客ID:', parsedData);
              setUser(parsedData);
              setLoginType('guest');
              setIsAuthenticated(false); // 自动生成的用户需要手动登录才能获得token
            }
          } catch (error) {
            console.error('❌ 解析自动生成的用户数据失败:', error);
          }
        }
      }
    } catch (error) {
      console.error('❌ AuthContext loadUserInfo 失败:', error);
    }
  };

  const login = async (userData: UserInfo, type: string) => {
    try {
      console.log('🔐 AuthContext login 开始:', { userData, type });
      await userService.saveUserLoginInfo(userData, type);
      console.log('🔐 AuthContext login 保存到本地存储完成');
      
      setUser(userData);
      setLoginType(type);
      setIsAuthenticated(true);
      
      console.log('🔐 AuthContext login 状态更新完成:', { 
        user: userData, 
        loginType: type, 
        isAuthenticated: true 
      });
      // 新增：登录后同步本地历史到云端
      await unifiedSyncService.addToSyncQueue({
        type: 'searchHistory',
        data: await AsyncStorage.getItem('searchHistory') || [],
        userId: userData.id,
        operation: 'update',
        priority: 'high'
      });
    } catch (error) {
      console.error('❌ AuthContext login 失败:', error);
      throw error;
    }
  };

  const logout = async () => {
    try {
      await userService.clearUserLoginInfo();
      setUser(null);
      setLoginType(null);
      setIsAuthenticated(false);
    } catch (error) {
      console.error('登出失败:', error);
    }
  };

  const updateUser = (userData: Partial<UserInfo>) => {
    if (user) {
      setUser({ ...user, ...userData });
    }
  };

  const getAuthToken = async (): Promise<string | null> => {
    try {
      return await userService.getAuthToken();
    } catch (error) {
      console.error('❌ AuthContext getAuthToken 失败:', error);
      return null;
    }
  };

  return (
    <AuthContext.Provider value={{ user, loginType, isAuthenticated, login, logout, updateUser, getAuthToken }}>
      {children}
    </AuthContext.Provider>
  );
}; 