services:
  - type: web
    name: dramaword-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WECHAT_APP_ID
        sync: false
      - key: WECHAT_APP_SECRET
        sync: false
      - key: WECHAT_BUNDLE_ID
        sync: false
      - key: APPLE_CLIENT_ID
        sync: false
      - key: APPLE_TEAM_ID
        sync: false
      - key: APPLE_KEY_ID
        sync: false
      - key: APPLE_PRIVATE_KEY
        sync: false
      - key: TMDB_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 